// Background-music tracks. The MP3s are pre-generated by
// `npm run music:generate` (ElevenLabs Music API) and live at
// /audio/music/<id>.mp3.

import type { Track } from "./music";

export const MENU_TRACK: Track = {
  id: "menu-theme",
  name: "Letra Theme",
  url: "/audio/music/menu-theme.mp3",
};

export const GAME_TRACKS: Track[] = [
  { id: "sunny-walk", name: "Sunny Walk", url: "/audio/music/sunny-walk.mp3" },
  { id: "letter-hop", name: "Letter Hop", url: "/audio/music/letter-hop.mp3" },
  { id: "adventure", name: "Adventure", url: "/audio/music/adventure.mp3" },
];

// Pick one game track per session. Stored in sessionStorage so navigating
// between menu and games doesn't keep re-rolling — the kid hears the same
// in-game track until they reload the page.
const SESSION_KEY = "letra:gameTrack";

export function pickGameTrack(): Track {
  try {
    const cached = sessionStorage.getItem(SESSION_KEY);
    if (cached) {
      const found = GAME_TRACKS.find((t) => t.id === cached);
      if (found) return found;
    }
  } catch {
    // sessionStorage may be unavailable — fall through to a fresh pick.
  }
  const choice = GAME_TRACKS[Math.floor(Math.random() * GAME_TRACKS.length)];
  try {
    sessionStorage.setItem(SESSION_KEY, choice.id);
  } catch {
    // Non-fatal.
  }
  return choice;
}
