// Background-music tracks. The MP3s are pre-generated by
// `npm run music:generate` (ElevenLabs Music API) and live at
// /audio/music/<id>.mp3.

import type { Track } from "./music";

export const MENU_TRACK: Track = {
  id: "menu-theme",
  name: "Letra Theme",
  url: "/audio/music/menu-theme.mp3",
};

// Plays during the alphabet-finished dance party. Pinned to 120 BPM
// in the generation prompt so the letter choreography in
// FindAlphabet can drive each move on the beat.
export const CELEBRATION_TRACK: Track = {
  id: "celebration",
  name: "Letter Party",
  url: "/audio/music/celebration.mp3",
};
// The dance choreography assumes this BPM. Keep in sync with the
// celebration prompt's "EXACTLY 120 BPM" hint in generate-music.ts.
export const CELEBRATION_BPM = 120;

export const GAME_TRACKS: Track[] = [
  { id: "sunny-walk", name: "Sunny Walk", url: "/audio/music/sunny-walk.mp3" },
  { id: "letter-hop", name: "Letter Hop", url: "/audio/music/letter-hop.mp3" },
  { id: "adventure", name: "Adventure", url: "/audio/music/adventure.mp3" },
  { id: "sky-park", name: "Sky Park", url: "/audio/music/sky-park.mp3" },
  { id: "bouncy-castle", name: "Bouncy Castle", url: "/audio/music/bouncy-castle.mp3" },
];

// Pick a fresh random game track each time an activity starts. Avoid
// repeating the immediately previous pick so the kid gets variety even
// across consecutive games.
let lastPickedId: string | null = null;

export function pickGameTrack(): Track {
  if (GAME_TRACKS.length === 1) return GAME_TRACKS[0];
  let choice: Track;
  do {
    choice = GAME_TRACKS[Math.floor(Math.random() * GAME_TRACKS.length)];
  } while (choice.id === lastPickedId);
  lastPickedId = choice.id;
  return choice;
}
