// Background-music tracks. The MP3s are pre-generated by
// `npm run music:generate` (ElevenLabs Music API) and live at
// /audio/music/<id>.mp3.

import type { Track } from "./music";

export const MENU_TRACK: Track = {
  id: "menu-theme",
  name: "Letra Theme",
  url: "/audio/music/menu-theme.mp3",
};

// Plays during the alphabet-finished dance party. Pinned to 120 BPM
// in the generation prompt so the letter choreography in
// FindAlphabet can drive each move on the beat.
export const CELEBRATION_TRACK: Track = {
  id: "celebration",
  name: "Letter Party",
  url: "/audio/music/celebration.mp3",
};
// The dance choreography assumes this BPM. Keep in sync with the
// celebration prompt's "EXACTLY 120 BPM" hint in generate-music.ts.
export const CELEBRATION_BPM = 120;

export const GAME_TRACKS: Track[] = [
  { id: "sunny-walk", name: "Sunny Walk", url: "/audio/music/sunny-walk.mp3" },
  { id: "letter-hop", name: "Letter Hop", url: "/audio/music/letter-hop.mp3" },
  { id: "adventure", name: "Adventure", url: "/audio/music/adventure.mp3" },
  { id: "sky-park", name: "Sky Park", url: "/audio/music/sky-park.mp3" },
  { id: "bouncy-castle", name: "Bouncy Castle", url: "/audio/music/bouncy-castle.mp3" },
  { id: "island-breeze", name: "Island Breeze", url: "/audio/music/island-breeze.mp3" },
];

// Some worlds have a signature track that should usually play there,
// without pinning it so hard that the world only ever has one tune.
const SIGNATURE_TRACKS: Record<string, { id: string; chance: number }> = {
  ocean: { id: "island-breeze", chance: 0.75 },
};

// Pick a fresh random game track each time an activity starts. Avoid
// repeating the immediately previous pick so the kid gets variety even
// across consecutive games.
//
// The no-repeat rule is deliberately NOT applied to a signature pick:
// on the ocean the whole point is that Island Breeze usually plays, and
// suppressing it just because it played last time would cap it at every
// other visit however high the chance is set.
let lastPickedId: string | null = null;

export function pickGameTrack(biomeId?: string): Track {
  if (GAME_TRACKS.length === 1) return GAME_TRACKS[0];
  const signature = biomeId ? SIGNATURE_TRACKS[biomeId] : undefined;
  if (signature && Math.random() < signature.chance) {
    const track = GAME_TRACKS.find((t) => t.id === signature.id);
    if (track) {
      lastPickedId = track.id;
      return track;
    }
  }
  // Otherwise roll from everything *except* the signature track, so the
  // remaining share is spread across the rest of the pool rather than
  // handing the signature track extra draws on top of its own chance.
  const pool = signature ? GAME_TRACKS.filter((t) => t.id !== signature.id) : GAME_TRACKS;
  let choice: Track;
  do {
    choice = pool[Math.floor(Math.random() * pool.length)];
  } while (pool.length > 1 && choice.id === lastPickedId);
  lastPickedId = choice.id;
  return choice;
}
