// Trophy registry — single source of truth for the achievement system.
//
// Image assets live in public/trophies/<id>.png and are generated by
// scripts/generate-trophies.ts. Keep the id list here in sync with the
// TROPHIES array in that script — the generated png filenames must
// match the id field exactly.
//
// Each trophy has a "kind":
//   - "stack": every time the milestone fires, the count increments and
//     an earned-modal pops with "Now ×N". Used for repeatable wins
//     (spell a particular word; finish A→Z in a particular case;
//     match a sound).
//   - "milestone": one-shot achievement. Earned modal shows once, count
//     stays at 1 forever (unless trophies are reset). Used for tier-up
//     style rewards like "spelled 25 words total".
//
// The shelf renders trophies in this declared order, so think of this
// as the on-screen layout from top-left to bottom-right.

export type TrophyId =
  | "alphabet-upper"
  | "alphabet-lower"
  | "alphabet-mixed"
  | "spell-cat"
  | "spell-dog"
  | "spell-sun"
  | "spell-bus"
  | "spell-pig"
  | "spell-tree"
  | "spell-star"
  | "spell-book"
  | "spell-ball"
  | "spell-cake"
  | "spell-hen"
  | "sound-match"
  | "word-wizard";

export type TrophyKind = "stack" | "milestone";

export type TrophySpec = {
  id: TrophyId;
  // Short display name (spoken aloud on tap, shown small under the tile).
  name: string;
  // Tile background colour on the shelf — picked to make the trophy art pop.
  tileColor: string;
  // What the kid did to earn it. One short sentence; surfaces in the
  // earn modal under the trophy and on the shelf as accessibility text.
  trigger: string;
  // Stack vs one-shot.
  kind: TrophyKind;
  // Emoji fallback used when the PNG is missing (e.g. asset gen failed,
  // running before scripts/generate-trophies.ts has been run).
  fallbackEmoji: string;
};

export const TROPHIES: TrophySpec[] = [
  {
    id: "alphabet-upper",
    name: "Big-Letter Hero",
    tileColor: "#ffd56b", // honey gold
    trigger: "Find every UPPERCASE letter from A to Z",
    kind: "stack",
    fallbackEmoji: "🅰️",
  },
  {
    id: "alphabet-lower",
    name: "Little-Letter Hero",
    tileColor: "#9bdc4a", // mint
    trigger: "Find every lowercase letter from a to z",
    kind: "stack",
    fallbackEmoji: "🔡",
  },
  {
    id: "alphabet-mixed",
    name: "Mix-Up Master",
    tileColor: "#c4a8ff", // lilac
    trigger: "Find every letter when cases are mixed",
    kind: "stack",
    fallbackEmoji: "🔠",
  },
  {
    id: "spell-cat",
    name: "Cat Catcher",
    tileColor: "#ffb084", // soft peach
    trigger: "Spell CAT five times",
    kind: "stack",
    fallbackEmoji: "🐱",
  },
  {
    id: "spell-dog",
    name: "Pup Finder",
    tileColor: "#ffd56b",
    trigger: "Spell DOG five times",
    kind: "stack",
    fallbackEmoji: "🐶",
  },
  {
    id: "spell-sun",
    name: "Sunbeam",
    tileColor: "#ffe066",
    trigger: "Spell SUN five times",
    kind: "stack",
    fallbackEmoji: "☀️",
  },
  {
    id: "spell-bus",
    name: "Bus Driver",
    tileColor: "#fff19a",
    trigger: "Spell BUS five times",
    kind: "stack",
    fallbackEmoji: "🚌",
  },
  {
    id: "spell-pig",
    name: "Pig Pal",
    tileColor: "#ffb6c8",
    trigger: "Spell PIG five times",
    kind: "stack",
    fallbackEmoji: "🐷",
  },
  {
    id: "spell-tree",
    name: "Tree Friend",
    tileColor: "#a8e0a8", // soft leaf green
    trigger: "Spell TREE five times",
    kind: "stack",
    fallbackEmoji: "🌳",
  },
  {
    id: "spell-star",
    name: "Shooting Star",
    tileColor: "#b8d4ff", // sky blue
    trigger: "Spell STAR five times",
    kind: "stack",
    fallbackEmoji: "⭐",
  },
  {
    id: "spell-book",
    name: "Bookworm",
    tileColor: "#e8c08c", // warm parchment tan
    trigger: "Spell BOOK five times",
    kind: "stack",
    fallbackEmoji: "📖",
  },
  {
    id: "spell-ball",
    name: "Ball Champ",
    tileColor: "#ff9a8a", // coral
    trigger: "Spell BALL five times",
    kind: "stack",
    fallbackEmoji: "⚽",
  },
  {
    id: "spell-cake",
    name: "Cake Day",
    tileColor: "#ffd6e3", // pale frosting pink
    trigger: "Spell CAKE five times",
    kind: "stack",
    fallbackEmoji: "🎂",
  },
  {
    id: "spell-hen",
    name: "Hen Buddy",
    tileColor: "#f0b878", // apricot
    trigger: "Spell HEN five times",
    kind: "stack",
    fallbackEmoji: "🐔",
  },
  {
    id: "sound-match",
    name: "Listening Star",
    tileColor: "#ff8aaa",
    trigger: "Match a letter sound to the right letter",
    kind: "stack",
    fallbackEmoji: "👂",
  },
  {
    id: "word-wizard",
    name: "Word Wizard",
    tileColor: "#c4a8ff",
    trigger: "Spell 25 words altogether",
    kind: "milestone",
    fallbackEmoji: "🧙",
  },
];

const BY_ID: Record<TrophyId, TrophySpec> = TROPHIES.reduce(
  (acc, t) => {
    acc[t.id] = t;
    return acc;
  },
  {} as Record<TrophyId, TrophySpec>,
);

export function getTrophy(id: TrophyId): TrophySpec {
  return BY_ID[id];
}

export const ALL_TROPHY_IDS: TrophyId[] = TROPHIES.map((t) => t.id);

// Total spell-the-word completions needed for the Word Wizard milestone.
// Lives here so games and the trophy lab share one constant.
export const WORD_WIZARD_THRESHOLD = 25;

// How many times the kid must spell the SAME word before earning that
// word's trophy (and then again before stacking +1). Tuned so each
// trophy feels like a real achievement instead of an instant reward
// after a single play.
export const SPELL_REPS_PER_TROPHY = 5;

// All per-word spell trophies. Word Wizard fires when the SUM of all
// per-word completion counts reaches WORD_WIZARD_THRESHOLD — that's
// "spelled 25 words across any combination."
export const SPELL_TROPHY_IDS: TrophyId[] = [
  "spell-cat",
  "spell-dog",
  "spell-sun",
  "spell-bus",
  "spell-pig",
  "spell-tree",
  "spell-star",
  "spell-book",
  "spell-ball",
  "spell-cake",
  "spell-hen",
];
